// Dữ liệu luyện nghe phản xạ tiếng Nhật (Choukai - 聴解)
// Mô phỏng các dạng đề thi JLPT thực tế (Mondai 1, Mondai 2: Nghe hiểu tác vụ & Chọn đáp án)

export const LISTENING_DRILLS = [
  // === N5: CĂN BẢN ===
  {
    id: 'l1',
    level: 'N5',
    title: 'Hỏi giờ tàu khởi hành tại Ga',
    scenario: 'Ở quầy thông tin nhà ga, một hành khách hỏi nhân viên về giờ tàu chạy đi Tokyo.',
    audioScript: '男の人と女の人が話しています。東京行きの電車は何時に出発しますか。\n\n男：すみません、東京行きの次の電車は何時ですか。\n女：ええと、次は十時十五分発です。\n男：十時十五分ですね。ありがとうございます。\n\n質問：東京行きの電車は何時に出発しますか。',
    speakerJp: 'すみません、東京行きの次の電車は何時ですか。ええと、次は十時十五分発です。',
    question: '東京行きの電車は何時に出発しますか？ (Tàu đi Tokyo khởi hành lúc mấy giờ?)',
    options: [
      { text: '10時05分 (10:05)', isCorrect: false },
      { text: '10時15分 (10:15)', isCorrect: true },
      { text: '10時50分 (10:50)', isCorrect: false },
      { text: '11時15分 (11:15)', isCorrect: false },
    ],
    transcriptVn: 'Người đàn ông và người phụ nữ đang nói chuyện. Chuyến tàu tiếp theo đi Tokyo khởi hành lúc mấy giờ?\nNam: Xin lỗi, chuyến tàu tiếp theo đi Tokyo là mấy giờ ạ?\nNữ: À, chuyến tiếp theo là 10 giờ 15 phút khởi hành.\nNam: 10 giờ 15 phút đúng không ạ. Xin cảm ơn.',
    explanation: 'Người phụ nữ nói rõ:「次は十時十五分（じゅうじじゅうごふん）発です」➔ Đáp án chính xác là 10h15.',
    keywords: ['東京行き (Đi Tokyo)', '十時十五分 (10h15)', '出発 (Khởi hành)'],
  },
  {
    id: 'l2',
    level: 'N5',
    title: 'Gọi món ăn tại quán Ramen',
    scenario: 'Khách hàng đang gọi món tại một quán mì Ramen ở Tokyo.',
    audioScript: 'レストランで男の人と店員が話しています。男の人は何を注文しましたか。\n\n店員：いらっしゃいませ。ご注文はお決まりですか。\n男：はい、味噌ラーメンを一つと、ウーロン茶をお願いします。\n店員：かしこまりました。味噌ラーメンとお茶ですね。\n\n質問：男の人は何を注文しましたか。',
    speakerJp: 'はい、味噌ラーメンを一つと、ウーロン茶をお願いします。かしこまりました。',
    question: '男の人は何を注文しましたか？ (Người đàn ông đã gọi món gì?)',
    options: [
      { text: 'Mì Shoyu ramen và bia', isCorrect: false },
      { text: 'Mì Miso ramen và trà ô long', isCorrect: true },
      { text: 'Cơm chiên và nước ngọt', isCorrect: false },
      { text: 'Mì Miso ramen và bánh gyoza', isCorrect: false },
    ],
    transcriptVn: 'Tại nhà hàng, người đàn ông và nhân viên đang nói chuyện.\nNhân viên: Kính chào quý khách! Quý khách đã chọn được món chưa ạ?\nNam: Vâng, cho tôi một bát Miso ramen và một trà ô long nhé.\nNhân viên: Vâng tôi hiểu rồi. Miso ramen và trà đúng không ạ.',
    explanation: 'Người đàn ông nói rõ:「味噌（みそ）ラーメンを一つと、ウーロン茶（ちゃ）をお願いします」➔ Chọn Miso ramen và trà ô long.',
    keywords: ['味噌ラーメン (Mì Miso)', 'ウーロン茶 (Trà ô long)', '注文 (Gọi món)'],
  },
  {
    id: 'l3',
    level: 'N5',
    title: 'Hẹn ngày giờ gặp mặt bạn bè',
    scenario: 'Hai người bạn đang bàn bạc chọn ngày đi xem phim cùng nhau vào cuối tuần.',
    audioScript: '女の人と男の人が電話で話しています。二人は何曜日に会いますか。\n\n女：もしもし、今週末の映画、土曜日に見に行かない？\n男：あ、土曜日はちょっと仕事があるんだ。日曜日はどう？\n女：日曜日ね、大丈夫だよ。じゃあ、日曜日の午後に会おう。\n\n質問：二人は何曜日に会いますか。',
    speakerJp: '土曜日はちょっと仕事があるんだ。日曜日はどう？じゃあ、日曜日の午後に会おう。',
    question: '二人は何曜日に会いますか？ (Hai người sẽ gặp nhau vào thứ mấy?)',
    options: [
      { text: 'Thứ Sáu (金曜日)', isCorrect: false },
      { text: 'Thứ Bảy (土曜日)', isCorrect: false },
      { text: 'Chủ Nhật (日曜日)', isCorrect: true },
      { text: 'Thứ Hai tuần sau (月曜日)', isCorrect: false },
    ],
    transcriptVn: 'Nữ: Alo, phim cuối tuần này, thứ Bảy cùng đi xem nhé?\nNam: A, thứ Bảy tớ bận chút công việc rồi. Chủ Nhật thì sao?\nNữ: Chủ Nhật à, được đấy. Vậy hẹn gặp nhau vào chiều Chủ Nhật nhé.',
    explanation: 'Thứ Bảy người nam bận việc「土曜日は仕事がある」, người nam đề xuất Chủ Nhật「日曜日はどう」và bạn nữ đồng ý「日曜日の午後に会おう」➔ Đáp án là Chủ Nhật.',
    keywords: ['土曜日 (Thứ Bảy)', '日曜日 (Chủ Nhật)', '会う (Gặp gỡ)'],
  },

  // === N4: SƠ CẤP ===
  {
    id: 'l4',
    level: 'N4',
    title: 'Hỏi đường đến Bưu điện',
    scenario: 'Một người đi bộ hỏi đường nhân viên cảnh sát tại bốt gác Koban.',
    audioScript: '道で男の人と警察官が話しています。郵便局はどこにありますか。\n\n男：すみません、この近くに郵便局はありますか。\n警察官：はい、この道をまっすぐ行って、二つ目の交差点を右に曲がってください。銀行の隣にありますよ。\n男：二つ目の交差点を右、銀行の隣ですね。分かりました。\n\n質問：郵便局はどこにありますか。',
    speakerJp: 'この道をまっすぐ行って、二つ目の交差点を右に曲がってください。銀行の隣にありますよ。',
    question: '郵便局はどこにありますか？ (Bưu điện nằm ở vị trí nào?)',
    options: [
      { text: 'Ngã tư thứ nhất rẽ trái, đối diện ngân hàng', isCorrect: false },
      { text: 'Đi thẳng, rẽ phải ở ngã tư thứ 2, cạnh ngân hàng', isCorrect: true },
      { text: 'Đi thẳng đến cuối đường, bên trong siêu thị', isCorrect: false },
      { text: 'Ngã tư thứ 2 rẽ trái, sau lưng trường học', isCorrect: false },
    ],
    transcriptVn: 'Cảnh sát hướng dẫn: Đi thẳng con đường này, đến ngã tư thứ 2 thì rẽ phải. Bưu điện nằm ngay bên cạnh ngân hàng đấy.',
    explanation: 'Từ khóa định hướng:「まっすぐ（Đi thẳng）」,「二つ目の交差点（Ngã tư thứ 2）」,「右に曲がる（Rẽ phải）」,「銀行の隣（Bên cạnh ngân hàng）」.',
    keywords: ['交差点 (Ngã tư)', '右に曲がる (Rẽ phải)', '隣 (Bên cạnh)'],
  },
  {
    id: 'l5',
    level: 'N4',
    title: 'Thông báo trên tàu điện ngầm',
    scenario: 'Hành khách nghe phát thanh trên tàu điện tuyến Yamanote.',
    audioScript: '電車のアナウンスを聞いてください。\n\nアナウンス：まもなく新宿、新宿です。お出口は左側です。中央線、総武線はお乗り換えです。お忘れ物のないよう、ご注意ください。\n\n質問：電車の出口はどちら側ですか。',
    speakerJp: 'まもなく新宿、新宿です。お出口は左側です。中央線はお乗り換えです。',
    question: '電車の出口はどちら側ですか？ (Cửa mở tàu điện ở phía bên nào?)',
    options: [
      { text: 'Cửa bên phải (右側 - Migigawa)', isCorrect: false },
      { text: 'Cửa bên trái (左側 - Hidarigawa)', isCorrect: true },
      { text: 'Cả hai cửa đều mở', isCorrect: false },
      { text: 'Chỉ mở toa đầu tiên', isCorrect: false },
    ],
    transcriptVn: 'Phát thanh trên tàu: Sắp tới ga Shinjuku, ga Shinjuku. Cửa ra ở phía bên tay trái. Quý khách chuyển sang tuyến Chuo Line xin mời đổi tàu. Xin quý khách chú ý không để quên hành lý.',
    explanation: 'Thông báo nêu rõ:「お出口は左側（ひだりがわ）です」➔ Cửa mở ở phía bên trái.',
    keywords: ['お出口 (Cửa ra)', '左側 (Bên trái)', 'お乗り換え (Đổi tàu)'],
  },

  // === N3: TRUNG CẤP ===
  {
    id: 'l6',
    level: 'N3',
    title: 'Họp công ty & Thay đổi lịch trình',
    scenario: 'Trưởng phòng thông báo cho nhân viên về việc thay đổi địa điểm và thời gian cuộc họp dự án.',
    audioScript: '会社で部長と社員が話しています。明日の会議の場所はどこになりましたか。\n\n部長：山田さん、明日の新プロジェクトの会議なんだけど、参加者が増えたから、第三会議室から大会議室に変更になったよ。\n社員：分かりました。時間は予定通り午後三時からでしょうか。\n部長：うん、時間は変更なしだ。プロジェクターの準備をお願いね。\n\n質問：明日の会議の場所はどこですか。',
    speakerJp: '参加者が増えたから、第三会議室から大会議室に変更になったよ。時間は変更なしだ。',
    question: '明日の会議の場所はどこになりましたか？ (Địa điểm họp ngày mai đã đổi sang đâu?)',
    options: [
      { text: 'Phòng họp số 3 (第三会議室)', isCorrect: false },
      { text: 'Phòng họp lớn (大会議室 - Dai Kaigishitsu)', isCorrect: true },
      { text: 'Phòng làm việc của Trưởng phòng', isCorrect: false },
      { text: 'Họp trực tuyến qua Zoom', isCorrect: false },
    ],
    transcriptVn: 'Trưởng phòng: Yamada à, cuộc họp dự án mới ngày mai vì số lượng người tham gia tăng lên nên đã chuyển từ Phòng họp 3 sang Phòng họp lớn (大会議室) rồi nhé.\nNhân viên: Vâng em hiểu rồi. Thời gian vẫn 3h chiều như kế hoạch chứ ạ?\nTrưởng phòng: Ừ, thời gian không thay đổi. Nhờ cậu chuẩn bị máy chiếu nhé.',
    explanation: 'Trưởng phòng nói:「第三会議室から大会議室に変更になったよ」➔ Ban đầu là phòng số 3 nhưng đã chuyển sang Phòng họp lớn (大会議室).',
    keywords: ['大会議室 (Phòng họp lớn)', '変更 (Thay đổi)', '予定通り (Như kế hoạch)'],
  },
];
