// Dữ liệu Đọc hiểu Dokkai (Truyện dân gian, văn hóa Nhật Bản) kèm Furigana và từ vựng

export const READING_ARTICLES = [
  {
    id: 'dokkai_1',
    level: 'N5',
    title: '桃太郎（ももたろう）',
    subtitle: 'Truyện cổ tích dân gian: Cậu bé quả đào',
    coverIcon: '🍑',
    content: [
      {
        segments: [
          { text: '昔々', ruby: 'むかしむかし', meaning: 'Ngày xửa ngày xưa' },
          { text: '、ある', meaning: 'có một' },
          { text: '所', ruby: 'ところ', meaning: 'nơi' },
          { text: 'に', meaning: 'ở' },
          { text: 'お爺さん', ruby: 'おじいさん', meaning: 'ông lão' },
          { text: 'と', meaning: 'và' },
          { text: 'お婆さん', ruby: 'おばあさん', meaning: 'bà lão' },
          { text: 'が', meaning: 'trợ từ chủ ngữ' },
          { text: '住んでいました', ruby: 'すんでいました', meaning: 'đã sinh sống' },
          { text: '。' },
        ],
      },
      {
        segments: [
          { text: 'お爺さん', ruby: 'おじいさん', meaning: 'ông lão' },
          { text: 'は', meaning: 'thì' },
          { text: '山', ruby: 'やま', meaning: 'ngọn núi' },
          { text: 'へ', meaning: 'đến' },
          { text: '芝刈り', ruby: 'しばかり', meaning: 'kiếm củi' },
          { text: 'に、', meaning: 'để' },
          { text: 'お婆さん', ruby: 'おばあさん', meaning: 'bà lão' },
          { text: 'は', meaning: 'thì' },
          { text: '川', ruby: 'かわ', meaning: 'dòng sông' },
          { text: 'へ', meaning: 'ra' },
          { text: '洗濯', ruby: 'せんたく', meaning: 'giặt giũ' },
          { text: 'に', meaning: 'để' },
          { text: '行きました', ruby: 'いきました', meaning: 'đã đi' },
          { text: '。' },
        ],
      },
      {
        segments: [
          { text: '川', ruby: 'かわ', meaning: 'dòng sông' },
          { text: 'から', meaning: 'từ' },
          { text: '大きな', ruby: 'おおきな', meaning: 'to lớn' },
          { text: '桃', ruby: 'もも', meaning: 'quả đào' },
          { text: 'が', meaning: 'trợ từ' },
          { text: 'どんぶらこ、どんぶらこ', meaning: 'bập bềnh trôi' },
          { text: 'と', meaning: 'rằng' },
          { text: '流れてきました', ruby: 'ながれてきました', meaning: 'trôi dạt tới' },
          { text: '。' },
        ],
      },
      {
        segments: [
          { text: '桃', ruby: 'もも', meaning: 'quả đào' },
          { text: 'を', meaning: 'trợ từ đối tượng' },
          { text: '切ると', ruby: 'きると', meaning: 'khi bổ ra' },
          { text: '、中', ruby: 'なか', meaning: 'bên trong' },
          { text: 'から', meaning: 'từ' },
          { text: '元気な', ruby: 'げんきな', meaning: 'khỏe mạnh' },
          { text: '男の子', ruby: 'おとのこ', meaning: 'cậu bé trai' },
          { text: 'が', meaning: 'trợ từ' },
          { text: '生まれました', ruby: 'うまれました', meaning: 'đã sinh ra' },
          { text: '。' },
        ],
      },
    ],
    translationVn:
      'Ngày xửa ngày xưa, ở một nơi nọ có một ông lão và một bà lão cùng chung sống. Ông lão lên núi đốn củi, còn bà lão ra sông giặt đồ. Từ thượng nguồn con sông, một quả đào khổng lồ bập bềnh trôi dạt tới. Khi bổ quả đào ra, một cậu bé kháu khỉnh, khỏe mạnh liền chào đời.',
    quiz: {
      question: 'お婆さんは川で何を拾いましたか？ (Bà lão đã nhặt được cái gì ở dòng sông?)',
      options: ['大きな魚 (Con cá to)', '大きな桃 (Quả đào to)', '小さなお金 (Một ít tiền)', '綺麗な石 (Viên đá đẹp)'],
      correct: 1,
      explanation: 'Trong bài có câu: 「川から大きな桃が...流れてきました」(Từ dòng sông, một quả đào lớn đã trôi dạt tới).',
    },
  },
  {
    id: 'dokkai_2',
    level: 'N4',
    title: '日本の桜と花見文化',
    subtitle: 'Văn hóa hoa anh đào và thưởng hoa Hanami',
    coverIcon: '🌸',
    content: [
      {
        segments: [
          { text: '春', ruby: 'はる', meaning: 'Mùa xuân' },
          { text: 'になると、', meaning: 'khi đến,' },
          { text: '日本', ruby: 'にほん', meaning: 'Nhật Bản' },
          { text: 'では', meaning: 'ở' },
          { text: '桜', ruby: 'さくら', meaning: 'hoa anh đào' },
          { text: 'が', meaning: 'trợ từ' },
          { text: '綺麗に', ruby: 'きれいに', meaning: 'rực rỡ' },
          { text: '咲きます', ruby: 'さきます', meaning: 'nở rộ' },
          { text: '。' },
        ],
      },
      {
        segments: [
          { text: '人々', ruby: 'ひとびと', meaning: 'Mọi người' },
          { text: 'は', meaning: 'thì' },
          { text: '公園', ruby: 'こうえん', meaning: 'công viên' },
          { text: 'に', meaning: 'tới' },
          { text: '集まって', ruby: 'あつまって', meaning: 'tụ tập lại' },
          { text: '、「花見」', ruby: 'はなみ', meaning: 'ngắm hoa Hanami' },
          { text: 'を', meaning: 'trợ từ' },
          { text: '楽しんだり', ruby: 'たのしんだり', meaning: 'vừa tận hưởng' },
          { text: '、美味しい', ruby: 'おいしい', meaning: 'ngon lành' },
          { text: 'お弁当', ruby: 'おべんとう', meaning: 'cơm hộp bento' },
          { text: 'を', meaning: 'trợ từ' },
          { text: '食べたり', ruby: 'たべたり', meaning: 'vừa thưởng thức' },
          { text: 'します。' },
        ],
      },
      {
        segments: [
          { text: '桜', ruby: 'さくら', meaning: 'Hoa anh đào' },
          { text: 'の', meaning: 'của' },
          { text: '花', ruby: 'はな', meaning: 'cánh hoa' },
          { text: 'は', meaning: 'thì' },
          { text: '一週間', ruby: 'いっしゅうかん', meaning: 'khoảng 1 tuần' },
          { text: 'ほどで', meaning: 'trong vòng' },
          { text: '散ってしまいます', ruby: 'ちってしまいます', meaning: 'sẽ rụng tàn' },
          { text: 'が、その', meaning: 'nhưng điều đó' },
          { text: '儚い', ruby: 'はかない', meaning: 'ngắn ngủi, mong manh' },
          { text: '美しさ', ruby: 'うつくしさ', meaning: 'vẻ đẹp' },
          { text: 'こそが', meaning: 'chính là' },
          { text: '日本人の', ruby: 'にほんじんの', meaning: 'của người Nhật' },
          { text: '心', ruby: 'こころ', meaning: 'trái tim' },
          { text: 'に', meaning: 'vào' },
          { text: '響きます', ruby: 'ひびきます', meaning: 'rung cảm sâu sắc' },
          { text: '。' },
        ],
      },
    ],
    translationVn:
      'Khi mùa xuân đến, hoa anh đào nở rộ rực rỡ khắp Nhật Bản. Mọi người tụ tập tại các công viên để cùng nhau ngắm hoa (Hanami), thưởng thức những hộp cơm bento ngon miệng. Dù hoa anh đào chỉ nở rộ rồi rụng chỉ trong khoảng một tuần, nhưng chính vẻ đẹp mong manh, hữu hạn ấy đã chạm đến sâu thẳm tâm hồn người Nhật.',
    quiz: {
      question: '日本人は桜の下で何を食べますか？ (Người Nhật thường ăn gì dưới tán hoa anh đào?)',
      options: ['ラーメン (Mì ramen)', 'お弁当 (Cơm hộp bento)', 'ステーキ (Bít tết bò)', 'ピザ (Pizza)'],
      correct: 1,
      explanation: 'Trong bài có câu: 「美味しいお弁当を食べたりします」(Thưởng thức những hộp cơm bento ngon lành).',
    },
  },
];
