// Dữ liệu từ vựng tiếng Nhật cốt lõi (Tango - 単語)
// Phân loại theo cấp độ JLPT (N5, N4, N3) và theo Chủ đề thông dụng trong đời sống Nhật Bản.

export const VOCAB_TOPICS = [
  { id: 'all', name: 'Tất cả chủ đề', icon: '🌸' },
  { id: 'greetings', name: 'Chào hỏi & Giao tiếp', icon: '🤝' },
  { id: 'food', name: 'Ẩm thực & Quán ăn', icon: '🍜' },
  { id: 'travel', name: 'Đi lại & Du lịch', icon: '🚃' },
  { id: 'shopping', name: 'Mua sắm & Tiền bạc', icon: '🛍️' },
  { id: 'daily', name: 'Đời sống & Sinh hoạt', icon: '🏠' },
  { id: 'work', name: 'Công việc & Trường học', icon: '💼' },
  { id: 'health', name: 'Sức khỏe & Cơ thể', icon: '🏥' },
  { id: 'time', name: 'Thời gian & Thời tiết', icon: '⏰' },
];

export const VOCAB_DATA = [
  // === CHỦ ĐỀ: CHÀO HỎI & GIAO TIẾP ===
  {
    id: 'v1',
    kanji: '初めまして',
    reading: 'はじめまして',
    romaji: 'hajimemashite',
    hanViet: 'SƠ',
    meaning: 'Rất hân hạnh được gặp bạn (lần đầu)',
    level: 'N5',
    topic: 'greetings',
    type: 'Thán từ',
    exampleJp: '初めまして、ナムと申します。',
    exampleVn: 'Rất hân hạnh được gặp bạn, tôi tên là Nam.',
  },
  {
    id: 'v2',
    kanji: '有難うございます',
    reading: 'ありがとうございます',
    romaji: 'arigatou gozaimasu',
    hanViet: 'HỮU NAN',
    meaning: 'Xin cảm ơn bạn rất nhiều',
    level: 'N5',
    topic: 'greetings',
    type: 'Thán từ',
    exampleJp: '手伝ってくれて、ありがとうございます。',
    exampleVn: 'Cảm ơn bạn rất nhiều vì đã giúp đỡ tôi.',
  },
  {
    id: 'v3',
    kanji: '失礼します',
    reading: 'しつれいします',
    romaji: 'shitsurei shimasu',
    hanViet: 'THẤT LỄ',
    meaning: 'Xin phép thất lễ / Xin phép vào phòng',
    level: 'N5',
    topic: 'greetings',
    type: 'Động từ',
    exampleJp: 'お先に失礼します。お疲れ様でした。',
    exampleVn: 'Tôi xin phép về trước. Mọi người đã vất vả rồi.',
  },
  {
    id: 'v4',
    kanji: '宜しくお願いします',
    reading: 'よろしくおねがいします',
    romaji: 'yoroshiku onegaishimasu',
    hanViet: 'NGHI NGUYỆN',
    meaning: 'Rất mong nhận được sự giúp đỡ',
    level: 'N5',
    topic: 'greetings',
    type: 'Thán từ',
    exampleJp: '今年もお世話になります。よろしくお願いします。',
    exampleVn: 'Năm nay cũng mong nhận được sự giúp đỡ của bạn.',
  },
  {
    id: 'v5',
    kanji: 'お疲れ様',
    reading: 'おつかれさま',
    romaji: 'otsukaresama',
    hanViet: 'BÌ DẠNG',
    meaning: 'Bạn đã vất vả rồi (lời chào sau giờ làm)',
    level: 'N4',
    topic: 'greetings',
    type: 'Thán từ',
    exampleJp: '今日の仕事もお疲れ様でした！',
    exampleVn: 'Hôm nay làm việc mọi người cũng vất vả rồi nhé!',
  },

  // === CHỦ ĐỀ: ẨM THỰC & QUÁN ĂN ===
  {
    id: 'v6',
    kanji: '料理',
    reading: 'りょうり',
    romaji: 'ryouri',
    hanViet: 'LIỆU LÝ',
    meaning: 'Món ăn, ẩm thực, nấu nướng',
    level: 'N5',
    topic: 'food',
    type: 'Danh từ',
    exampleJp: '日本料理で寿司が一番好きです。',
    exampleVn: 'Trong các món ăn Nhật Bản tôi thích sushi nhất.',
  },
  {
    id: 'v7',
    kanji: '美味しい',
    reading: 'おいしい',
    romaji: 'oishii',
    hanViet: 'MỸ VỊ',
    meaning: 'Ngon miệng',
    level: 'N5',
    topic: 'food',
    type: 'Tính từ đuôi い',
    exampleJp: 'このラーメンのスープはとても美味しい。',
    exampleVn: 'Nước dùng của tô mì ramen này rất ngon.',
  },
  {
    id: 'v8',
    kanji: '注文',
    reading: 'ちゅうもん',
    romaji: 'chuumon',
    hanViet: 'CHÚ VĂN',
    meaning: 'Gọi món, đặt hàng (order)',
    level: 'N4',
    topic: 'food',
    type: 'Danh từ / Động từ する',
    exampleJp: 'すみません、注文をお願いします。',
    exampleVn: 'Xin lỗi, cho tôi gọi món với ạ.',
  },
  {
    id: 'v9',
    kanji: '乾杯',
    reading: 'かんぱい',
    romaji: 'kanpai',
    hanViet: 'CAN BÔI',
    meaning: 'Cạn ly, cụng ly (Chúc mừng)',
    level: 'N5',
    topic: 'food',
    type: 'Danh từ',
    exampleJp: '皆さんの健康のために、乾杯！',
    exampleVn: 'Vì sức khỏe của tất cả mọi người, cạn ly!',
  },
  {
    id: 'v10',
    kanji: '定食',
    reading: 'ていしょく',
    romaji: 'teishoku',
    hanViet: 'ĐỊNH THỰC',
    meaning: 'Suất cơm phần, set cơm trưa',
    level: 'N4',
    topic: 'food',
    type: 'Danh từ',
    exampleJp: 'お昼は焼き魚定食を食べました。',
    exampleVn: 'Bữa trưa tôi đã ăn set cơm cá nướng.',
  },
  {
    id: 'v11',
    kanji: '居酒屋',
    reading: 'いざかや',
    romaji: 'izakaya',
    hanViet: 'CƯ TỬU ỐC',
    meaning: 'Quán nhậu truyền thống kiểu Nhật',
    level: 'N4',
    topic: 'food',
    type: 'Danh từ',
    exampleJp: '仕事の後に同僚と居酒屋へ行きました。',
    exampleVn: 'Sau giờ làm tôi cùng đồng nghiệp đến quán nhậu.',
  },

  // === CHỦ ĐỀ: ĐI LẠI & DU LỊCH ===
  {
    id: 'v12',
    kanji: '電車',
    reading: 'でんしゃ',
    romaji: 'densha',
    hanViet: 'ĐIỆN XA',
    meaning: 'Tàu điện',
    level: 'N5',
    topic: 'travel',
    type: 'Danh từ',
    exampleJp: '毎朝、電車で学校へ通っています。',
    exampleVn: 'Mỗi buổi sáng tôi đều đi tàu điện đến trường.',
  },
  {
    id: 'v13',
    kanji: '切符',
    reading: 'きっぷ',
    romaji: 'kippu',
    hanViet: 'THIẾT PHÙ',
    meaning: 'Vé xe, vé tàu',
    level: 'N5',
    topic: 'travel',
    type: 'Danh từ',
    exampleJp: '自動券売機で電車の切符を買いました。',
    exampleVn: 'Tôi đã mua vé tàu ở máy bán vé tự động.',
  },
  {
    id: 'v14',
    kanji: '新幹線',
    reading: 'しんかんせん',
    romaji: 'shinkansen',
    hanViet: 'TÂN CÁN TUYẾN',
    meaning: 'Tàu cao tốc Shinkansen',
    level: 'N4',
    topic: 'travel',
    type: 'Danh từ',
    exampleJp: '東京から京都まで新幹線で二時間半です。',
    exampleVn: 'Từ Tokyo đến Kyoto đi tàu Shinkansen mất 2 tiếng rưỡi.',
  },
  {
    id: 'v15',
    kanji: '案内',
    reading: 'あんない',
    romaji: 'annai',
    hanViet: 'ÁN NỘI',
    meaning: 'Hướng dẫn, dẫn đường',
    level: 'N4',
    topic: 'travel',
    type: 'Danh từ / Động từ する',
    exampleJp: '明日、街の名所を案内しますね。',
    exampleVn: 'Ngày mai tôi sẽ dẫn bạn đi tham quan các danh lam thắng cảnh trong thành phố nhé.',
  },
  {
    id: 'v16',
    kanji: '旅館',
    reading: 'りょかん',
    romaji: 'ryokan',
    hanViet: 'LỮ QUÁN',
    meaning: 'Nhà trọ truyền thống kiểu Nhật',
    level: 'N4',
    topic: 'travel',
    type: 'Danh từ',
    exampleJp: '温泉のある古い旅館に泊まりました。',
    exampleVn: 'Chúng tôi đã nghỉ tại một lữ quán cổ có suối nước nóng.',
  },

  // === CHỦ ĐỀ: MUA SẮM & TIỀN BẠC ===
  {
    id: 'v17',
    kanji: '買い物',
    reading: 'かいもの',
    romaji: 'kaimono',
    hanViet: 'MÃI VẬT',
    meaning: 'Mua sắm đồ đạc',
    level: 'N5',
    topic: 'shopping',
    type: 'Danh từ',
    exampleJp: '週末にデパートへ買い物に行きます。',
    exampleVn: 'Cuối tuần tôi đi mua sắm ở trung tâm thương mại.',
  },
  {
    id: 'v18',
    kanji: '値段',
    reading: 'ねだん',
    romaji: 'nedan',
    hanViet: 'TRỊ ĐOẠN',
    meaning: 'Giá cả, mức giá',
    level: 'N4',
    topic: 'shopping',
    type: 'Danh từ',
    exampleJp: '品質が良くて値段も手頃です。',
    exampleVn: 'Chất lượng tốt mà giá cả lại phải chăng.',
  },
  {
    id: 'v19',
    kanji: '割引',
    reading: 'わりびき',
    romaji: 'waribiki',
    hanViet: 'CÁT DẪN',
    meaning: 'Giảm giá, chiết khấu',
    level: 'N4',
    topic: 'shopping',
    type: 'Danh từ',
    exampleJp: 'この商品は二割引き（20% off）になっています。',
    exampleVn: 'Mặt hàng này đang được giảm giá 20%.',
  },
  {
    id: 'v20',
    kanji: 'お釣り',
    reading: 'おつり',
    romaji: 'otsuri',
    hanViet: 'ĐIẾU',
    meaning: 'Tiền thối, tiền thừa trả lại',
    level: 'N4',
    topic: 'shopping',
    type: 'Danh từ',
    exampleJp: 'レシートとお釣りをお受け取りください。',
    exampleVn: 'Xin quý khách nhận lại hóa đơn và tiền thừa.',
  },

  // === CHỦ ĐỀ: ĐỜI SỐNG & SINH HOẠT ===
  {
    id: 'v21',
    kanji: '生活',
    reading: 'せいかつ',
    romaji: 'seikatsu',
    hanViet: 'SINH HOẠT',
    meaning: 'Đời sống, sinh hoạt thường ngày',
    level: 'N4',
    topic: 'daily',
    type: 'Danh từ / Động từ する',
    exampleJp: '日本での一人暮らし生活に慣れました。',
    exampleVn: 'Tôi đã quen với cuộc sống tự lập một mình ở Nhật Bản.',
  },
  {
    id: 'v22',
    kanji: '部屋',
    reading: 'へや',
    romaji: 'heya',
    hanViet: 'BỘ ỐC',
    meaning: 'Căn phòng',
    level: 'N5',
    topic: 'daily',
    type: 'Danh từ',
    exampleJp: '日当たりが良くて静かな部屋です。',
    exampleVn: 'Căn phòng đón ánh nắng tốt và rất yên tĩnh.',
  },
  {
    id: 'v23',
    kanji: '習慣',
    reading: 'しゅうかん',
    romaji: 'shuukan',
    hanViet: 'TẬP QUÁN',
    meaning: 'Thói quen, phong tục',
    level: 'N4',
    topic: 'daily',
    type: 'Danh từ',
    exampleJp: '玄関で靴を脱ぐのが日本の習慣です。',
    exampleVn: 'Cởi giày ở hiên cửa là phong tục tập quán của Nhật Bản.',
  },
  {
    id: 'v24',
    kanji: '約束',
    reading: 'やくそく',
    romaji: 'yakusoku',
    hanViet: 'ƯỚC THÚC',
    meaning: 'Lời hứa, cuộc hẹn',
    level: 'N4',
    topic: 'daily',
    type: 'Danh từ / Động từ する',
    exampleJp: '友達と会う約束があります。',
    exampleVn: 'Tôi có một cuộc hẹn gặp gỡ bạn bè.',
  },

  // === CHỦ ĐỀ: CÔNG VIỆC & TRƯỜNG HỌC ===
  {
    id: 'v25',
    kanji: '仕事',
    reading: 'しごと',
    romaji: 'shigoto',
    hanViet: 'SĨ SỰ',
    meaning: 'Công việc',
    level: 'N5',
    topic: 'work',
    type: 'Danh từ',
    exampleJp: 'IT企業でプログラマーの仕事をしています。',
    exampleVn: 'Tôi đang làm công việc lập trình viên tại một công ty IT.',
  },
  {
    id: 'v26',
    kanji: '会議',
    reading: 'かいぎ',
    romaji: 'kaigi',
    hanViet: 'HỘI NGHỊ',
    meaning: 'Cuộc họp, hội nghị',
    level: 'N4',
    topic: 'work',
    type: 'Danh từ',
    exampleJp: '午後二時から重要な会議が始まります。',
    exampleVn: 'Từ 2 giờ chiều cuộc họp quan trọng sẽ bắt đầu.',
  },
  {
    id: 'v27',
    kanji: '試験',
    reading: 'しけん',
    romaji: 'shiken',
    hanViet: 'THÍ NGHIỆM',
    meaning: 'Kỳ thi, bài kiểm tra',
    level: 'N5',
    topic: 'work',
    type: 'Danh từ',
    exampleJp: '来月、JLPT N2の試験を受けます。',
    exampleVn: 'Tháng sau tôi sẽ tham gia kỳ thi JLPT N2.',
  },
  {
    id: 'v28',
    kanji: '経験',
    reading: 'けいけん',
    romaji: 'keiken',
    hanViet: 'KINH NGHIỆM',
    meaning: 'Kinh nghiệm, trải nghiệm',
    level: 'N4',
    topic: 'work',
    type: 'Danh từ / Động từ する',
    exampleJp: '日本で働いた経験はとても役に立ちました。',
    exampleVn: 'Kinh nghiệm làm việc tại Nhật Bản đã giúp ích cho tôi rất nhiều.',
  },

  // === CHỦ ĐỀ: SỨC KHỎE & CƠ THỂ ===
  {
    id: 'v29',
    kanji: '健康',
    reading: 'けんこう',
    romaji: 'kenkou',
    hanViet: 'KIỆN KHANG',
    meaning: 'Sức khỏe',
    level: 'N4',
    topic: 'health',
    type: 'Danh từ / Tính từ な',
    exampleJp: '健康のために、毎日野菜をたくさん食べます。',
    exampleVn: 'Vì sức khỏe, mỗi ngày tôi đều ăn thật nhiều rau củ.',
  },
  {
    id: 'v30',
    kanji: '病院',
    reading: 'びょういん',
    romaji: 'byouin',
    hanViet: 'BỆNH VIỆN',
    meaning: 'Bệnh viện',
    level: 'N5',
    topic: 'health',
    type: 'Danh từ',
    exampleJp: '風邪を引いたので、病院へ行きました。',
    exampleVn: 'Vì bị cảm lạnh nên tôi đã đến bệnh viện khám.',
  },
  {
    id: 'v31',
    kanji: '大丈夫',
    reading: 'だいじょうぶ',
    romaji: 'daijoubu',
    hanViet: 'ĐẠI TRƯỢNG PHU',
    meaning: 'Không sao, ổn thỏa',
    level: 'N5',
    topic: 'health',
    type: 'Tính từ な',
    exampleJp: '気分が悪そうですが、大丈夫ですか。',
    exampleVn: 'Trông bạn có vẻ mệt, bạn có sao không?',
  },

  // === CHỦ ĐỀ: THỜI GIAN & THỜI TIẾT ===
  {
    id: 'v32',
    kanji: '時間',
    reading: 'じかん',
    romaji: 'jikan',
    hanViet: 'THỜI GIAN',
    meaning: 'Thời gian, giờ giấc',
    level: 'N5',
    topic: 'time',
    type: 'Danh từ',
    exampleJp: '時間通りに駅に着きました。',
    exampleVn: 'Tôi đã đến ga đúng giờ hẹn.',
  },
  {
    id: 'v33',
    kanji: '天気',
    reading: 'てんき',
    romaji: 'tenki',
    hanViet: 'THIÊN KHÍ',
    meaning: 'Thời tiết',
    level: 'N5',
    topic: 'time',
    type: 'Danh từ',
    exampleJp: '今日は天気が良くて気持ちがいいです。',
    exampleVn: 'Hôm nay thời tiết đẹp thật dễ chịu.',
  },
  {
    id: 'v34',
    kanji: '季節',
    reading: 'きせつ',
    romaji: 'kisetsu',
    hanViet: 'QUÝ TIẾT',
    meaning: 'Mùa trong năm',
    level: 'N4',
    topic: 'time',
    type: 'Danh từ',
    exampleJp: '日本の四季の中で、秋が一番好きです。',
    exampleVn: 'Trong 4 mùa của Nhật Bản, tôi thích mùa thu nhất.',
  },
  {
    id: 'v35',
    kanji: '将来',
    reading: 'しょうらい',
    romaji: 'shourai',
    hanViet: 'TƯƠNG LAI',
    meaning: 'Tương lai gần, sau này',
    level: 'N4',
    topic: 'time',
    type: 'Danh từ',
    exampleJp: '将来、日本で自分の会社を作りたいです。',
    exampleVn: 'Tương lai, tôi muốn thành lập công ty của riêng mình tại Nhật Bản.',
  },

  // === TRUNG CẤP N3 MỞ RỘNG ===
  {
    id: 'v36',
    kanji: '遠慮',
    reading: 'えんりょ',
    romaji: 'enryo',
    hanViet: 'VIỄN LỰ',
    meaning: 'Ngại ngùng, khách khí',
    level: 'N3',
    topic: 'greetings',
    type: 'Danh từ / Động từ する',
    exampleJp: 'どうぞご遠慮なくお召し上がりください。',
    exampleVn: 'Xin mời dùng tự nhiên, đừng ngại ạ.',
  },
  {
    id: 'v37',
    kanji: '感謝',
    reading: 'かんしゃ',
    romaji: 'kansha',
    hanViet: 'CẢM TẠ',
    meaning: 'Lòng biết ơn, cảm kích',
    level: 'N3',
    topic: 'greetings',
    type: 'Danh từ / Động từ する',
    exampleJp: '先生のご指導に深く感謝しております。',
    exampleVn: 'Em xin bày tỏ lòng biết ơn sâu sắc đối với sự chỉ dạy của thầy cô.',
  },
  {
    id: 'v38',
    kanji: '雰囲気',
    reading: 'ふんいき',
    romaji: 'funiki',
    hanViet: 'PHÂN VI KHÍ',
    meaning: 'Bầu không khí, cảm giác không gian',
    level: 'N3',
    topic: 'food',
    type: 'Danh từ',
    exampleJp: 'この喫茶店は落ち着いた雰囲気で居心地がいい。',
    exampleVn: 'Quán cà phê này có bầu không khí trầm ấm, dễ chịu.',
  },
  {
    id: 'v39',
    kanji: '景色',
    reading: 'けしき',
    romaji: 'keshiki',
    hanViet: 'CẢNH SẮC',
    meaning: 'Phong cảnh, cảnh sắc thiên nhiên',
    level: 'N3',
    topic: 'travel',
    type: 'Danh từ',
    exampleJp: '山頂からの景色は息をのむほど美しかった。',
    exampleVn: 'Phong cảnh nhìn từ đỉnh núi đẹp đến ngạt thở.',
  },
  {
    id: 'v40',
    kanji: '目標',
    reading: 'もくひょう',
    romaji: 'mokuhyou',
    hanViet: 'MỤC TIÊU',
    meaning: 'Mục tiêu, đích đến',
    level: 'N3',
    topic: 'work',
    type: 'Danh từ',
    exampleJp: '今年中にJLPT N1合格という目標を達成したい。',
    exampleVn: 'Tôi muốn hoàn thành mục tiêu đỗ JLPT N1 trong năm nay.',
  },
];
